
services:
  traefik:
    image: "traefik:v3.4"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"

      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"

      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=brendan.bank@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    env_file: "../.env"
    ports:
      - "${HTTP_PORT:-8080}:80"    # HTTP - configurable via HTTP_PORT env var
      - "${HTTPS_PORT:-8443}:443"  # HTTPS - configurable via HTTPS_PORT env var
      - "${TRAEFIK_DASHBOARD_PORT:-8081}:8080"  # Traefik dashboard - configurable via TRAEFIK_DASHBOARD_PORT env var
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    logging:
      driver: "loki"
      options:
        loki-url: "http://loki.bgwlan.nl:3100/loki/api/v1/push"
        loki-pipeline-stages: |
          - json:
              expressions:
                stream: stream
                attrs: attrs
                tag: attrs.tag
                level: attrs.level
                msg: log
        loki-relabel-config: |
          - action: replace
            source_labels: ['__filename__']
            target_label: 'job'
          - action: replace
            source_labels: ['container_name']
            target_label: 'container'
          - action: replace
            source_labels: ['stream']
            target_label: 'stream'
    networks:
      - web-network # Traefik will be on this network
    restart: unless-stopped # Ensure Traefik restarts if it crashes or the host reboots

  bcourse:
    container_name: "bcourse"
    build: ..
    image: bcourse:latest
    # Remove direct port mapping, Traefik will handle routing
    # ports:
    #   - "8081:8080"
    env_file: "../.env"

    logging:
      driver: "loki"
      options:
        loki-url: "http://loki.bgwlan.nl:3100/loki/api/v1/push"
        loki-pipeline-stages: |
          - json:
              expressions:
                stream: stream
                attrs: attrs
                tag: attrs.tag
                level: attrs.level
                msg: log
        loki-relabel-config: |
          - action: replace
            source_labels: ['__filename__']
            target_label: 'job'
          - action: replace
            source_labels: ['container_name']
            target_label: 'container'
          - action: replace
            source_labels: ['stream']
            target_label: 'stream'
    networks:
      - web-network # Connect bcourse to the same network as Traefik
    labels:
      - "traefik.enable=true" # Enable Traefik for this service
      - "traefik.http.routers.bcourse.rule=Host(`${TRAEFIK_HOST1:-localhost}`) || Host(`${TRAEFIK_HOST2:-dev.bcourse.nl}`)"
      - "traefik.http.routers.bcourse.entrypoints=web,websecure" # Both HTTP and HTTPS entrypoints
      - "traefik.http.routers.bcourse.tls.certresolver=myresolver" # Use Let's Encrypt for HTTPS
      - "traefik.http.services.bcourse.loadbalancer.server.port=80" # Tell Traefik the internal port of your app
    restart: unless-stopped # Ensure Traefik restarts if it crashes or the host reboots

  mysql:
    image: mysql:8.0
    container_name: "bcourse-mysql"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-bcourse}
      MYSQL_USER: ${MYSQL_USER:-bcourse}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-bcoursepassword}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    env_file: "../.env"
    ports:
      - "${MYSQL_PORT:-3307}:3306"  # MySQL - configurable via MYSQL_PORT env var
    networks:
      - web-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    logging:
      driver: "loki"
      options:
        loki-url: "http://loki.bgwlan.nl:3100/loki/api/v1/push"
        loki-pipeline-stages: |
          - json:
              expressions:
                stream: stream
                attrs: attrs
                tag: attrs.tag
                level: attrs.level
                msg: log
        loki-relabel-config: |
          - action: replace
            source_labels: ['__filename__']
            target_label: 'job'
          - action: replace
            source_labels: ['container_name']
            target_label: 'container'
          - action: replace
            source_labels: ['stream']
            target_label: 'stream'
    command: --default-authentication-plugin=caching_sha2_password

volumes:
  mysql_data:

networks:
  web-network:
    driver: bridge # This is the network for Traefik and your web services

