"""add active to training

Revision ID: 012592f43031
Revises: 6d2adf0456b0
Create Date: 2025-03-17 21:18:34.821546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '012592f43031'
down_revision = '6d2adf0456b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training', schema=None) as batch_op:
        batch_op.drop_column('active')

    # ### end Alembic commands ###
