"""Add TranslationFeedback table

Revision ID: 2db8c0eefe63
Revises: 1fb72b769031
Create Date: 2026-04-09 09:22:54.586072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2db8c0eefe63'
down_revision = '1fb72b769031'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translation_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('lang', sa.String(length=10), nullable=False),
    sa.Column('page_title', sa.String(length=256), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('translation_feedback')
    # ### end Alembic commands ###


def upgrade_postalcodes():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_postalcodes():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

