"""Add automation_trainingtypes association table

Revision ID: 5e53e1606698
Revises: add_paid_field
Create Date: 2026-03-03 13:48:29.047143

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5e53e1606698'
down_revision = 'add_paid_field'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    op.create_table('automation_trainingtypes',
    sa.Column('automation_schedule_id', sa.Integer(), nullable=False),
    sa.Column('trainingtype_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['automation_schedule_id'], ['automation_schedule.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trainingtype_id'], ['training_type.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('automation_schedule_id', 'trainingtype_id')
    )


def downgrade_():
    op.drop_table('automation_trainingtypes')


def upgrade_postalcodes():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_postalcodes():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

