"""Add msg_transactional_emails to user_settings

Revision ID: 6071def18e8a
Revises: 5e53e1606698
Create Date: 2026-03-10 16:46:35.655360

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '6071def18e8a'
down_revision = '5e53e1606698'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('msg_transactional_emails', sa.Boolean(), nullable=False, server_default=sa.text('1')))

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_column('msg_transactional_emails')

    # ### end Alembic commands ###


def upgrade_postalcodes():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_postalcodes():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

