"""empty message

Revision ID: 6d2adf0456b0
Revises: 6abfe9a461e5
Create Date: 2025-03-17 20:31:47.026254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d2adf0456b0'
down_revision = '6abfe9a461e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_participants', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training', schema=None) as batch_op:
        batch_op.drop_column('max_participants')

    # ### end Alembic commands ###
