"""Initial migration.

Revision ID: 71edd4096b48
Revises: 
Create Date: 2025-03-15 08:26:04.630881

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '71edd4096b48'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_status', schema=None) as batch_op:
        batch_op.drop_index('userstatus')

    op.drop_table('user_status')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'client_status', ['status_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_ibfk_1', 'user_status', ['status_id'], ['id'])

    op.create_table('user_status',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('userstatus', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('user_status', schema=None) as batch_op:
        batch_op.create_index('userstatus', ['userstatus'], unique=True)

    # ### end Alembic commands ###
