"""support

Revision ID: 841e8462a7aa
Revises: 
Create Date: 2025-08-12 21:45:30.944676

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '841e8462a7aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('support_ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('practice_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['practice_id'], ['practice.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('apscheduler_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_apscheduler_jobs_next_run_time')

    op.drop_table('apscheduler_jobs')
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apscheduler_jobs',
    sa.Column('id', mysql.VARCHAR(length=191), nullable=False),
    sa.Column('next_run_time', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('job_state', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('apscheduler_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_apscheduler_jobs_next_run_time', ['next_run_time'], unique=False)

    op.drop_table('support_ticket')
    # ### end Alembic commands ###


def upgrade_postalcodes():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('postalcodes',
    sa.Column('postcode', sa.String(length=32), nullable=False),
    sa.Column('huisnummer', sa.String(length=32), nullable=False),
    sa.Column('straat', sa.String(length=256), nullable=False),
    sa.Column('buurt', sa.String(length=256), nullable=False),
    sa.Column('wijk', sa.String(length=256), nullable=False),
    sa.Column('woonplaats', sa.String(length=256), nullable=False),
    sa.Column('gemeente', sa.String(length=256), nullable=False),
    sa.Column('provincie', sa.String(length=256), nullable=False),
    sa.Column('latitude', sa.Double(), nullable=False),
    sa.Column('longitude', sa.Double(), nullable=False),
    sa.PrimaryKeyConstraint('postcode', 'huisnummer')
    )
    # ### end Alembic commands ###


def downgrade_postalcodes():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('postalcodes')
    # ### end Alembic commands ###

