"""description to training types.

Revision ID: fedda0f9c68a
Revises: 52ae2ac9380b
Create Date: 2025-03-16 16:20:50.817560

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fedda0f9c68a'
down_revision = '52ae2ac9380b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('training_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_type', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('training', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', mysql.TEXT(), nullable=True))

    # ### end Alembic commands ###
